/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Adicionales.PlaceHolder;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectointegrador.BaseDatos;
import proyectointegrador.Carrito;
import proyectointegrador.Empresa;
import proyectointegrador.Venta;
import proyectointegrador.Factura;
import proyectointegrador.Producto;
import com.google.common.base.Preconditions;
/**
 *
 * @author GPatr
 */
public class VistaFactura extends javax.swing.JFrame {

    Calendar fecha_actual=new GregorianCalendar();
    /**
     * Creates new form VistaFactura
     */
    public VistaFactura() {
        initComponents();
        jdFecha_actual.setCalendar(fecha_actual);
        cargarEmpresas();
        cargarDatosVenta();
        // Asigna placeholders en los campos de texto
        PlaceHolder Subtotal = new PlaceHolder("Subtotal", FacSubtotal);
        PlaceHolder Descuento = new PlaceHolder("Descuento", FacDescuento);
        PlaceHolder Total = new PlaceHolder("Total", FacTotal);
        PlaceHolder Pago = new PlaceHolder("Pago", FacPago);
        PlaceHolder Cambio = new PlaceHolder("Cambio", FacCambio);
        PlaceHolder RUC = new PlaceHolder("RUC de la empresa", FacRuc);
        PlaceHolder Nombre = new PlaceHolder("Nombre de la empresa", FacNombre);
        PlaceHolder Correo = new PlaceHolder("Correo de la empresa", FacCorreo);
    }
    
    //METODOS
    
    //METODOS
    
    public void cargarDatosVenta() {
    Venta venta = Venta.getVentaActual();

    if (venta != null) {
        FacSubtotal.setText(String.format("%.2f", venta.getSubtotal()));
        FacDescuento.setText(String.format("%.2f", venta.getTotalConDescuento() - venta.getSubtotal()));
        FacTotal.setText(String.format("%.2f", venta.getTotalConDescuento()));
        FacPago.setText(String.format("%.2f", venta.getSubtotal() + (venta.getTotalConDescuento() - venta.getSubtotal())));
        FacCambio.setText(String.format("%.2f", venta.getCambio()));
    }
    }
    
    
    /**
     * Este método se encarga de cargar las empresas disponibles en el sistema
     * en el JComboBox correspondiente (jComboBoxEmpresas). Primero limpia los
     * elementos actuales del JComboBox, luego obtiene la lista de empresas a
     * través del método obtenerEmpresas() de la clase Empresa y finalmente
     * agrega cada empresa al JComboBox.
     */
    
    private void cargarEmpresas() {
        List<Empresa> empresas = Empresa.obtenerEmpresas();
        for (Empresa empresa : empresas) {
            FacEmpresa.addItem(empresa);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        FacSubtotal = new javax.swing.JTextField();
        FacDescuento = new javax.swing.JTextField();
        FacTotal = new javax.swing.JTextField();
        FacPago = new javax.swing.JTextField();
        FacCambio = new javax.swing.JTextField();
        BotonAtrasF = new javax.swing.JButton();
        FacRuc = new javax.swing.JTextField();
        FacNombre = new javax.swing.JTextField();
        jdFecha_actual = new com.toedter.calendar.JDateChooser();
        FacCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BotonGenFac = new javax.swing.JButton();
        FacEmpresa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BotonCerrarF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(216, 255, 216));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 179, 255), 5));

        FacSubtotal.setBackground(new java.awt.Color(216, 255, 216));
        FacSubtotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FacSubtotal.setForeground(new java.awt.Color(0, 0, 0));

        FacDescuento.setBackground(new java.awt.Color(216, 255, 216));
        FacDescuento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FacDescuento.setForeground(new java.awt.Color(0, 0, 0));

        FacTotal.setBackground(new java.awt.Color(216, 255, 216));
        FacTotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FacTotal.setForeground(new java.awt.Color(0, 0, 0));

        FacPago.setBackground(new java.awt.Color(216, 255, 216));
        FacPago.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FacPago.setForeground(new java.awt.Color(0, 0, 0));

        FacCambio.setBackground(new java.awt.Color(216, 255, 216));
        FacCambio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FacCambio.setForeground(new java.awt.Color(0, 0, 0));

        BotonAtrasF.setBackground(new java.awt.Color(179, 217, 255));
        BotonAtrasF.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BotonAtrasF.setForeground(new java.awt.Color(0, 0, 0));
        BotonAtrasF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IcoBoletaVolver.png"))); // NOI18N
        BotonAtrasF.setText("Volver Atras");

        FacRuc.setBackground(new java.awt.Color(216, 255, 216));
        FacRuc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FacRuc.setForeground(new java.awt.Color(0, 0, 0));

        FacNombre.setBackground(new java.awt.Color(216, 255, 216));
        FacNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FacNombre.setForeground(new java.awt.Color(0, 0, 0));
        FacNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacNombreActionPerformed(evt);
            }
        });

        jdFecha_actual.setBackground(new java.awt.Color(216, 255, 216));
        jdFecha_actual.setDateFormatString("dd/MM/yyyy HH:mm:ss");

        FacCorreo.setBackground(new java.awt.Color(216, 255, 216));
        FacCorreo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FacCorreo.setForeground(new java.awt.Color(0, 0, 0));
        FacCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacCorreoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Empresa");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SubTotal");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Descuento");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pago");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cambio");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("RUC");

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Fecha");

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Correo");

        BotonGenFac.setBackground(new java.awt.Color(179, 217, 255));
        BotonGenFac.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BotonGenFac.setForeground(new java.awt.Color(0, 0, 0));
        BotonGenFac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IcoBoletagenerar.png"))); // NOI18N
        BotonGenFac.setText("Generar Factura");
        BotonGenFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGenFacActionPerformed(evt);
            }
        });

        FacEmpresa.setBackground(new java.awt.Color(216, 255, 216));
        FacEmpresa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FacEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        FacEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacEmpresaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Generar Factura");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IcoFactura.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(BotonAtrasF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(BotonGenFac)
                .addGap(93, 93, 93))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FacSubtotal)
                    .addComponent(FacDescuento)
                    .addComponent(FacTotal)
                    .addComponent(FacPago)
                    .addComponent(FacCambio)
                    .addComponent(FacEmpresa, 0, 183, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FacRuc)
                    .addComponent(FacNombre)
                    .addComponent(jdFecha_actual, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(FacCorreo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FacRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(FacEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FacSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FacNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FacDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel10))
                    .addComponent(jdFecha_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FacTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FacCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FacPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FacCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAtrasF)
                    .addComponent(BotonGenFac))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        BotonCerrarF.setBackground(new java.awt.Color(179, 217, 255));
        BotonCerrarF.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BotonCerrarF.setForeground(new java.awt.Color(0, 0, 0));
        BotonCerrarF.setText("Cerrar Sesión");
        BotonCerrarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonCerrarF)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonCerrarF)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FacNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacNombreActionPerformed

    private void BotonCerrarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarFActionPerformed
        // TODO add your handling code here:
        // Cerrar esta ventana
        this.dispose();

        // Abrir la ventana de Login
        Vistas.Login login = new Vistas.Login();
        login.setVisible(true);
    
    }//GEN-LAST:event_BotonCerrarFActionPerformed

    private void FacCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacCorreoActionPerformed

    private void FacEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacEmpresaActionPerformed
        // TODO add your handling code here:
        Empresa seleccionada = (Empresa) FacEmpresa.getSelectedItem();
            if (seleccionada != null) {
                System.out.println("Empresa seleccionada: " + seleccionada.getNombreEmpresa());
                System.out.println("ID: " + seleccionada.getIdempresa());
            }
    }//GEN-LAST:event_FacEmpresaActionPerformed

    private void BotonGenFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenFacActionPerformed
        // TODO add your handling code here:
        try {
            String ruc = FacRuc.getText().trim();
            String nombre = FacNombre.getText().trim();
            String correo = FacCorreo.getText().trim();
            Date fechaSeleccionada = jdFecha_actual.getDate();

            // Validaciones básicas
            Preconditions.checkArgument(!ruc.isEmpty(), "Ingrese el RUC.");
            Preconditions.checkArgument(!nombre.isEmpty(), "Ingrese el nombre.");
            Preconditions.checkArgument(!correo.isEmpty(), "Ingrese el correo.");
            Preconditions.checkNotNull(fechaSeleccionada, "Seleccione una fecha.");

            Empresa empresaSeleccionada = (Empresa) FacEmpresa.getSelectedItem();
            Preconditions.checkNotNull(empresaSeleccionada, "Seleccione una empresa.");

            int idEmpresa = empresaSeleccionada.getIdempresa();

            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
            String fecha = formatoFecha.format(fechaSeleccionada);
            String hora = formatoHora.format(fechaSeleccionada);

            int idTrabajador = Login.usuarioActual.getId();

            // Validar carrito
            Carrito carrito = Carrito.getInstancia();
            Preconditions.checkArgument(!carrito.getProductos().isEmpty(), "El carrito está vacío.");

            // Construir tabla para el PDF
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Nombre");
            modelo.addColumn("Cantidad");
            modelo.addColumn("Subtotal");

            for (Producto producto : carrito.getProductos()) {
                String nombreProd = producto.getNombre();
                int cantidad = producto.getStock();
                double subtotal = producto.getPrecio() * cantidad;
                modelo.addRow(new Object[]{nombreProd, cantidad, subtotal});
            }

            String total = FacTotal.getText().trim();
            String descuento = FacDescuento.getText().trim();
            Preconditions.checkArgument(!total.isEmpty(), "El total no puede estar vacío.");
            Preconditions.checkArgument(!descuento.isEmpty(), "El descuento no puede estar vacío.");

            // Registrar venta
            Venta venta = Venta.getVentaActual();
            BaseDatos bd = new BaseDatos();

            Factura facturapdf = new Factura(empresaSeleccionada, ruc, nombre, correo, total, descuento, modelo);
            boolean exito = venta.registrarVentaEnBD(bd, idTrabajador, fecha, hora, idEmpresa);

            if (exito) {
                String codigoFactura = facturapdf.generarPDF();
                Preconditions.checkNotNull(codigoFactura, "No se pudo generar el archivo de factura PDF.");

                int idVenta = venta.getIdVenta();
                Factura facturabd = new Factura(bd, ruc, nombre, correo, codigoFactura);
                facturabd.registrarComprobanteEnBD(bd, idVenta);

                JOptionPane.showMessageDialog(this, "Venta registrada correctamente.");
                carrito.limpiarCarrito();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar la venta.");
            }

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_BotonGenFacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtrasF;
    private javax.swing.JButton BotonCerrarF;
    private javax.swing.JButton BotonGenFac;
    private javax.swing.JTextField FacCambio;
    private javax.swing.JTextField FacCorreo;
    private javax.swing.JTextField FacDescuento;
    private javax.swing.JComboBox<Empresa> FacEmpresa;
    private javax.swing.JTextField FacNombre;
    private javax.swing.JTextField FacPago;
    private javax.swing.JTextField FacRuc;
    private javax.swing.JTextField FacSubtotal;
    private javax.swing.JTextField FacTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdFecha_actual;
    // End of variables declaration//GEN-END:variables
}
