/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import Modelos.Empresa;
import Modelos.Producto;
import Modelos.Venta;
import Modelos.Boleta ;
import java.util.Date;
import Modelos.BaseDatos;
import Modelos.Carrito;
import javax.swing.table.DefaultTableModel;
import Adicionales.PlaceHolder;
import Modelos.Usuario;
import com.google.common.base.Preconditions;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import javax.swing.JOptionPane;

/**
 * Esta clase representa la interfaz gráfica para la vista de boletas en el
 * sistema. Se encarga de mostrar la información relacionada con las boletas,
 * como la selección de la empresa, la fecha actual y otras funcionalidades
 * específicas relacionadas con la gestión de boletas. Extiende de
 * javax.swing.JFrame, lo que le permite ser una ventana dentro de la
 * aplicación.
 *
 * @author GPatr
 */
public class VistaBoleta extends javax.swing.JFrame {
    // Instancia un objeto Calendar para obtener la fecha actual

    Calendar fecha_actual = new GregorianCalendar();

    /**
     * Constructor de la clase VistaBoleta. Inicializa los componentes de la
     * ventana, establece el calendario con la fecha actual y carga las empresas
     * disponibles en el sistema.
     */
    public VistaBoleta() {
        initComponents();
        jdFecha_actual.setCalendar(fecha_actual);
        cargarEmpresas();
        cargarDatosVenta();
        // Asigna placeholders en los campos de texto
        PlaceHolder Subtotal = new PlaceHolder("Subtotal", BolSubtotal);
        PlaceHolder Descuento = new PlaceHolder("Descuento", BolDescuento);
        PlaceHolder Total = new PlaceHolder("Total", BolTotal);
        PlaceHolder Pago = new PlaceHolder("Pago", BolPago);
        PlaceHolder Cambio = new PlaceHolder("Cambio", BolCambio);
        PlaceHolder DNI = new PlaceHolder("DNI del cliente", BolDni);
        PlaceHolder Nombre = new PlaceHolder("Nombre del cliente", BolNombre);
    }
    
    //METODOS
    
    public void cargarDatosVenta() {
    Venta venta = Venta.getVentaActual();

    if (venta != null) {
        BolSubtotal.setText(String.format("%.2f", venta.getSubtotal()));
        BolDescuento.setText(String.format("%.2f", venta.getTotalConDescuento() - venta.getSubtotal()));
        BolTotal.setText(String.format("%.2f", venta.getTotalConDescuento()));
        BolPago.setText(String.format("%.2f", venta.getSubtotal() + (venta.getTotalConDescuento() - venta.getSubtotal())));
        BolCambio.setText(String.format("%.2f", venta.getCambio()));
    }
    }

    /**
     * Este método se encarga de cargar las empresas disponibles en el sistema
     * en el JComboBox correspondiente (jComboBoxEmpresas). Primero limpia los
     * elementos actuales del JComboBox, luego obtiene la lista de empresas a
     * través del método obtenerEmpresas() de la clase Empresa y finalmente
     * agrega cada empresa al JComboBox.
     */
    private void cargarEmpresas() {
        List<Empresa> empresas = Empresa.obtenerEmpresas();
        for (Empresa empresa : empresas) {
            BolEmpresa.addItem(empresa);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BolSubtotal = new javax.swing.JTextField();
        BolDescuento = new javax.swing.JTextField();
        BolTotal = new javax.swing.JTextField();
        BolPago = new javax.swing.JTextField();
        BolCambio = new javax.swing.JTextField();
        BolDni = new javax.swing.JTextField();
        BolNombre = new javax.swing.JTextField();
        BotonContableB = new javax.swing.JButton();
        BotonGenBol = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jdFecha_actual = new com.toedter.calendar.JDateChooser();
        BolEmpresa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BotonCerrarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(216, 255, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 179, 255), 5));

        BolSubtotal.setEditable(false);
        BolSubtotal.setBackground(new java.awt.Color(216, 255, 216));
        BolSubtotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BolSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        BolSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BolSubtotalActionPerformed(evt);
            }
        });

        BolDescuento.setBackground(new java.awt.Color(216, 255, 216));
        BolDescuento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BolDescuento.setForeground(new java.awt.Color(0, 0, 0));

        BolTotal.setBackground(new java.awt.Color(216, 255, 216));
        BolTotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BolTotal.setForeground(new java.awt.Color(0, 0, 0));

        BolPago.setBackground(new java.awt.Color(216, 255, 216));
        BolPago.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BolPago.setForeground(new java.awt.Color(0, 0, 0));

        BolCambio.setBackground(new java.awt.Color(216, 255, 216));
        BolCambio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BolCambio.setForeground(new java.awt.Color(0, 0, 0));

        BolDni.setBackground(new java.awt.Color(216, 255, 216));
        BolDni.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BolDni.setForeground(new java.awt.Color(0, 0, 0));
        BolDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BolDniActionPerformed(evt);
            }
        });

        BolNombre.setBackground(new java.awt.Color(216, 255, 216));
        BolNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BolNombre.setForeground(new java.awt.Color(0, 0, 0));

        BotonContableB.setBackground(new java.awt.Color(179, 217, 255));
        BotonContableB.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BotonContableB.setForeground(new java.awt.Color(0, 0, 0));
        BotonContableB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IcoBoletaVolver.png"))); // NOI18N
        BotonContableB.setText("Enviar al area Contable");
        BotonContableB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonContableBActionPerformed(evt);
            }
        });

        BotonGenBol.setBackground(new java.awt.Color(179, 217, 255));
        BotonGenBol.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BotonGenBol.setForeground(new java.awt.Color(0, 0, 0));
        BotonGenBol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IcoBoletagenerar.png"))); // NOI18N
        BotonGenBol.setText("Generar Boleta");
        BotonGenBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGenBolActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Empresa");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SubTotal");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Descuento");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pago");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cambio");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("DNI");

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Fecha");

        jdFecha_actual.setBackground(new java.awt.Color(216, 255, 216));
        jdFecha_actual.setForeground(new java.awt.Color(216, 255, 216));
        jdFecha_actual.setDateFormatString("dd/MM/yyyy HH:mm:ss");

        BolEmpresa.setBackground(new java.awt.Color(216, 255, 216));
        BolEmpresa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BolEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        BolEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BolEmpresaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Generar Boleta");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IcoBoleta.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(202, 202, 202))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(112, Short.MAX_VALUE)
                        .addComponent(BotonContableB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BolTotal)
                            .addComponent(BolPago)
                            .addComponent(BolCambio)
                            .addComponent(BolSubtotal)
                            .addComponent(BolDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(BolEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdFecha_actual, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(BolNombre)
                            .addComponent(BolDni))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BotonGenBol)
                        .addGap(111, 111, 111))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BolDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(BolEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BolSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BolNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BolDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BolTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BolPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BolCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jdFecha_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonContableB)
                    .addComponent(BotonGenBol))
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 32, -1, 400));

        BotonCerrarB.setBackground(new java.awt.Color(179, 217, 255));
        BotonCerrarB.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BotonCerrarB.setForeground(new java.awt.Color(0, 0, 0));
        BotonCerrarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IcoAdminexit.png"))); // NOI18N
        BotonCerrarB.setText("Cerrar Sesión");
        BotonCerrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarBActionPerformed(evt);
            }
        });
        jPanel1.add(BotonCerrarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BolDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BolDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BolDniActionPerformed

    private void BolEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BolEmpresaActionPerformed
        // TODO add your handling code here:
        Empresa seleccionada = (Empresa) BolEmpresa.getSelectedItem();
            if (seleccionada != null) {
                System.out.println("Empresa seleccionada: " + seleccionada.getNombreEmpresa());
                System.out.println("ID: " + seleccionada.getIdempresa());
            }
    }//GEN-LAST:event_BolEmpresaActionPerformed

    private void BolSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BolSubtotalActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_BolSubtotalActionPerformed

    private void BotonCerrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    
    }//GEN-LAST:event_BotonCerrarBActionPerformed

    private void BotonGenBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenBolActionPerformed
        // TODO add your handling code here:
        try {
            String dni = BolDni.getText().trim();
            String nombre = BolNombre.getText().trim();
            Date fechaSeleccionada = jdFecha_actual.getDate();

            // Validaciones de campos
            Preconditions.checkArgument(!dni.isEmpty(), "Ingrese el DNI.");
            Preconditions.checkArgument(!nombre.isEmpty(), "Ingrese el nombre.");
            Preconditions.checkNotNull(fechaSeleccionada, "Seleccione una fecha.");

            Empresa empresaSeleccionada = (Empresa) BolEmpresa.getSelectedItem();
            Preconditions.checkNotNull(empresaSeleccionada, "Seleccione una empresa.");

            int idEmpresa = empresaSeleccionada.getIdempresa();

            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
            String fecha = formatoFecha.format(fechaSeleccionada);
            String hora = formatoHora.format(fechaSeleccionada);

            Usuario actual = Usuario.getUsuarioActual();
            Preconditions.checkNotNull(actual, "No hay un usuario autenticado actualmente.");

            int idTrabajador = actual.getId();

            // Validar carrito
            Carrito carrito = Carrito.getInstancia();
            Preconditions.checkArgument(!carrito.getProductos().isEmpty(), "El carrito está vacío.");

            // Preparar tabla para PDF
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Nombre");
            modelo.addColumn("Cantidad");
            modelo.addColumn("Subtotal");

            for (Producto producto : carrito.getProductos()) {
                String nombreProd = producto.getNombre();
                int cantidad = producto.getStock();
                double subtotal = producto.getPrecio() * cantidad;
                modelo.addRow(new Object[]{nombreProd, cantidad, subtotal});
            }

            String total = BolTotal.getText().trim();
            String descuento = BolDescuento.getText().trim();
            Preconditions.checkArgument(!total.isEmpty(), "El total no puede estar vacío.");
            Preconditions.checkArgument(!descuento.isEmpty(), "El descuento no puede estar vacío.");

            // Registrar venta
            BaseDatos bd = new BaseDatos();
            Venta venta = Venta.getVentaActual();
            Boleta boletapdf = new Boleta(empresaSeleccionada, dni, nombre, total, descuento, modelo);

            boolean exito = venta.registrarVentaEnBD(bd, idTrabajador, fecha, hora, idEmpresa, "boleta");

            if (exito) {
                String codigoBoleta = boletapdf.generarPDF();
                Preconditions.checkNotNull(codigoBoleta, "No se pudo generar el archivo de boleta PDF.");

                int idVenta = venta.getIdVenta();
                Boleta boletabd = new Boleta(bd, dni, nombre, codigoBoleta);
                boletabd.registrarComprobanteEnBD(bd, idVenta);

                JOptionPane.showMessageDialog(this, "Venta registrada correctamente.");
                carrito.limpiarCarrito();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar la venta.");
            }

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_BotonGenBolActionPerformed

    private void BotonContableBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonContableBActionPerformed
    // TODO add your handling code here:
         try {
         URL url = new URL("http://localhost:8081/mensaje");
         HttpURLConnection con = (HttpURLConnection) url.openConnection();
         con.setRequestMethod("GET");

         // Detectar como Java client (esto ya lo hace por defecto)
         BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream(), "UTF-8"));
         StringBuilder mensaje = new StringBuilder();
         String line;
         while ((line = in.readLine()) != null) {
             mensaje.append(line).append("\n");
         }
         in.close();

         JOptionPane.showMessageDialog(null, mensaje.toString().trim(), "Confirmación de Contabilidad", JOptionPane.INFORMATION_MESSAGE);

     } catch (Exception ex) {
         ex.printStackTrace();
         JOptionPane.showMessageDialog(null, "❌ Error al contactar con el sistema contable.", "Error", JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_BotonContableBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaBoleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BolCambio;
    private javax.swing.JTextField BolDescuento;
    private javax.swing.JTextField BolDni;
    private javax.swing.JComboBox<Empresa> BolEmpresa;
    private javax.swing.JTextField BolNombre;
    private javax.swing.JTextField BolPago;
    private javax.swing.JTextField BolSubtotal;
    private javax.swing.JTextField BolTotal;
    private javax.swing.JButton BotonCerrarB;
    private javax.swing.JButton BotonContableB;
    private javax.swing.JButton BotonGenBol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdFecha_actual;
    // End of variables declaration//GEN-END:variables
}
